<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Mission\Deployment instead.
     * @deprecated
     */
    class Mission_Deployment {}
}
class_exists(Mission\Deployment::class);
@trigger_error('Pb\Mission_Deployment is deprecated and will be removed in the next major release. Use Pb\Mission\Deployment instead', E_USER_DEPRECATED);

