<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Mission\Objective instead.
     * @deprecated
     */
    class Mission_Objective {}
}
class_exists(Mission\Objective::class);
@trigger_error('Pb\Mission_Objective is deprecated and will be removed in the next major release. Use Pb\Mission\Objective instead', E_USER_DEPRECATED);

