<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace Pb;

use UnexpectedValueException;

/**
 * Protobuf type <code>pb.MissionFormat</code>
 */
class MissionFormat
{
    /**
     * Generated from protobuf enum <code>COMBAT_PATROL = 0;</code>
     */
    const COMBAT_PATROL = 0;
    /**
     * Generated from protobuf enum <code>INCURSION = 1;</code>
     */
    const INCURSION = 1;

    private static $valueToName = [
        self::COMBAT_PATROL => 'COMBAT_PATROL',
        self::INCURSION => 'INCURSION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

