<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace Pb;

if (false) {
    /**
     * This class is deprecated. Use Pb\Mission\Twist instead.
     * @deprecated
     */
    class Mission_Twist {}
}
class_exists(Mission\Twist::class);
@trigger_error('Pb\Mission_Twist is deprecated and will be removed in the next major release. Use Pb\Mission\Twist instead', E_USER_DEPRECATED);

