<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mission_generator.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Mission</code>
 */
class Mission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     */
    protected $rules = '';
    /**
     * Generated from protobuf field <code>.pb.MissionFormat MissionFormat = 4;</code>
     */
    protected $MissionFormat = 0;
    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Twist twists = 5;</code>
     */
    private $twists;
    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Objective objectives = 6;</code>
     */
    private $objectives;
    /**
     * Generated from protobuf field <code>.pb.Mission.Deployment deployment = 7;</code>
     */
    protected $deployment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $description
     *     @type string $rules
     *     @type int $MissionFormat
     *     @type \Pb\Mission\Twist[]|\Google\Protobuf\Internal\RepeatedField $twists
     *     @type \Pb\Mission\Objective[]|\Google\Protobuf\Internal\RepeatedField $objectives
     *     @type \Pb\Mission\Deployment $deployment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MissionGenerator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     * @return string
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>string rules = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRules($var)
    {
        GPBUtil::checkString($var, True);
        $this->rules = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.MissionFormat MissionFormat = 4;</code>
     * @return int
     */
    public function getMissionFormat()
    {
        return $this->MissionFormat;
    }

    /**
     * Generated from protobuf field <code>.pb.MissionFormat MissionFormat = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMissionFormat($var)
    {
        GPBUtil::checkEnum($var, \Pb\MissionFormat::class);
        $this->MissionFormat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Twist twists = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTwists()
    {
        return $this->twists;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Twist twists = 5;</code>
     * @param \Pb\Mission\Twist[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTwists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Mission\Twist::class);
        $this->twists = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Objective objectives = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjectives()
    {
        return $this->objectives;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Mission.Objective objectives = 6;</code>
     * @param \Pb\Mission\Objective[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjectives($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Mission\Objective::class);
        $this->objectives = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Mission.Deployment deployment = 7;</code>
     * @return \Pb\Mission\Deployment|null
     */
    public function getDeployment()
    {
        return $this->deployment;
    }

    public function hasDeployment()
    {
        return isset($this->deployment);
    }

    public function clearDeployment()
    {
        unset($this->deployment);
    }

    /**
     * Generated from protobuf field <code>.pb.Mission.Deployment deployment = 7;</code>
     * @param \Pb\Mission\Deployment $var
     * @return $this
     */
    public function setDeployment($var)
    {
        GPBUtil::checkMessage($var, \Pb\Mission\Deployment::class);
        $this->deployment = $var;

        return $this;
    }

}

