version: '3'
services:

    app:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        image: ${APP_NAME}-php
        container_name: "${APP_NAME}-app"
        restart: always
        tty: true
        environment:
            SERVICE_NAME: "${APP_NAME}-app"
            SERVICE_TAGS: dev
        working_dir: /var/www/
        user: ${UID}
        networks:
            - app-network
        volumes:
            - ./api-gateway:/var/www
            - ./docker/api-gateway/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    webserver:
        image: nginx:alpine
        container_name: "${APP_NAME}-webserver"
        restart: always
        tty: true
        ports:
            - "${API_PORT}:80"
        networks:
            - app-network
        volumes:
            - ./api-gateway:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    db:
        build: 
            context: ./docker/api-gateway/postgres
            dockerfile: Dockerfile
            args: 
                UID: ${UID}
                APP_NAME: ${APP_NAME}
        image: postgres
        restart: always
        container_name: "${APP_NAME}-db"
        user: "${UID}"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_USER}
        ports:
            - "${DB_PORT}:5432"
        networks:
            - app-network
        volumes:
            - ./docker/var/postgres/dbdata:/var/lib/postgresql/data

    go:
        image: ${APP_NAME}-mission-generator
        ports:
          - "${MG_PORT}:${MG_PORT}"
        networks:
          - app-network
        environment:
          APP_PORT: ${MG_PORT}
        env_file:
          - mission-generator/.env
        build: 
            dockerfile: Dockerfile
            context: ./mission-generator

networks:
    app-network:
        driver: bridge
