// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: mission_generator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissionFormat int32

const (
	MissionFormat_COMBAT_PATROL MissionFormat = 0
	MissionFormat_INCURSION     MissionFormat = 1
)

// Enum value maps for MissionFormat.
var (
	MissionFormat_name = map[int32]string{
		0: "COMBAT_PATROL",
		1: "INCURSION",
	}
	MissionFormat_value = map[string]int32{
		"COMBAT_PATROL": 0,
		"INCURSION":     1,
	}
)

func (x MissionFormat) Enum() *MissionFormat {
	p := new(MissionFormat)
	*p = x
	return p
}

func (x MissionFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_mission_generator_proto_enumTypes[0].Descriptor()
}

func (MissionFormat) Type() protoreflect.EnumType {
	return &file_mission_generator_proto_enumTypes[0]
}

func (x MissionFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissionFormat.Descriptor instead.
func (MissionFormat) EnumDescriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{0}
}

type GenerateMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionFormat MissionFormat `protobuf:"varint,1,opt,name=missionFormat,proto3,enum=pb.MissionFormat" json:"missionFormat,omitempty"`
}

func (x *GenerateMissionRequest) Reset() {
	*x = GenerateMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMissionRequest) ProtoMessage() {}

func (x *GenerateMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMissionRequest.ProtoReflect.Descriptor instead.
func (*GenerateMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateMissionRequest) GetMissionFormat() MissionFormat {
	if x != nil {
		return x.MissionFormat
	}
	return MissionFormat_COMBAT_PATROL
}

type Mission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title         string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules         string               `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	MissionFormat MissionFormat        `protobuf:"varint,4,opt,name=MissionFormat,proto3,enum=pb.MissionFormat" json:"MissionFormat,omitempty"`
	Twists        []*Mission_Twist     `protobuf:"bytes,5,rep,name=twists,proto3" json:"twists,omitempty"`
	Objectives    []*Mission_Objective `protobuf:"bytes,6,rep,name=objectives,proto3" json:"objectives,omitempty"`
	Deployment    *Mission_Deployment  `protobuf:"bytes,7,opt,name=deployment,proto3" json:"deployment,omitempty"`
}

func (x *Mission) Reset() {
	*x = Mission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{1}
}

func (x *Mission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Mission) GetMissionFormat() MissionFormat {
	if x != nil {
		return x.MissionFormat
	}
	return MissionFormat_COMBAT_PATROL
}

func (x *Mission) GetTwists() []*Mission_Twist {
	if x != nil {
		return x.Twists
	}
	return nil
}

func (x *Mission) GetObjectives() []*Mission_Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *Mission) GetDeployment() *Mission_Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type ListMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListMissionRequest) Reset() {
	*x = ListMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionRequest) ProtoMessage() {}

func (x *ListMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionRequest.ProtoReflect.Descriptor instead.
func (*ListMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{2}
}

func (x *ListMissionRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMissionRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Mission_Twist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules       string `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
}

func (x *Mission_Twist) Reset() {
	*x = Mission_Twist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Twist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Twist) ProtoMessage() {}

func (x *Mission_Twist) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Twist.ProtoReflect.Descriptor instead.
func (*Mission_Twist) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Mission_Twist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Twist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission_Twist) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type Mission_Objective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules       string `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
}

func (x *Mission_Objective) Reset() {
	*x = Mission_Objective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Objective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Objective) ProtoMessage() {}

func (x *Mission_Objective) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Objective.ProtoReflect.Descriptor instead.
func (*Mission_Objective) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Mission_Objective) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission_Objective) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Mission_Objective) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type Mission_Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *Mission_Deployment) Reset() {
	*x = Mission_Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mission_generator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission_Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission_Deployment) ProtoMessage() {}

func (x *Mission_Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_mission_generator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission_Deployment.ProtoReflect.Descriptor instead.
func (*Mission_Deployment) Descriptor() ([]byte, []int) {
	return file_mission_generator_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Mission_Deployment) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_mission_generator_proto protoreflect.FileDescriptor

var file_mission_generator_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x51, 0x0a,
	0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x52, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x22, 0x86, 0x04, 0x0a, 0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x52, 0x0d, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x74, 0x77, 0x69, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x77, 0x69, 0x73, 0x74, 0x52, 0x06, 0x74, 0x77, 0x69, 0x73, 0x74, 0x73, 0x12, 0x35,
	0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x55, 0x0a,
	0x05, 0x54, 0x77, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x1a, 0x59, 0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x1a,
	0x28, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x3e, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x31, 0x0a, 0x0d, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f,
	0x4d, 0x42, 0x41, 0x54, 0x5f, 0x50, 0x41, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x49, 0x4e, 0x43, 0x55, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x32, 0x76, 0x0a, 0x10,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x33, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x30, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mission_generator_proto_rawDescOnce sync.Once
	file_mission_generator_proto_rawDescData = file_mission_generator_proto_rawDesc
)

func file_mission_generator_proto_rawDescGZIP() []byte {
	file_mission_generator_proto_rawDescOnce.Do(func() {
		file_mission_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_mission_generator_proto_rawDescData)
	})
	return file_mission_generator_proto_rawDescData
}

var file_mission_generator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mission_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mission_generator_proto_goTypes = []interface{}{
	(MissionFormat)(0),             // 0: pb.MissionFormat
	(*GenerateMissionRequest)(nil), // 1: pb.GenerateMissionRequest
	(*Mission)(nil),                // 2: pb.Mission
	(*ListMissionRequest)(nil),     // 3: pb.ListMissionRequest
	(*Mission_Twist)(nil),          // 4: pb.Mission.Twist
	(*Mission_Objective)(nil),      // 5: pb.Mission.Objective
	(*Mission_Deployment)(nil),     // 6: pb.Mission.Deployment
}
var file_mission_generator_proto_depIdxs = []int32{
	0, // 0: pb.GenerateMissionRequest.missionFormat:type_name -> pb.MissionFormat
	0, // 1: pb.Mission.MissionFormat:type_name -> pb.MissionFormat
	4, // 2: pb.Mission.twists:type_name -> pb.Mission.Twist
	5, // 3: pb.Mission.objectives:type_name -> pb.Mission.Objective
	6, // 4: pb.Mission.deployment:type_name -> pb.Mission.Deployment
	1, // 5: pb.MissionGenerator.Generate:input_type -> pb.GenerateMissionRequest
	3, // 6: pb.MissionGenerator.List:input_type -> pb.ListMissionRequest
	2, // 7: pb.MissionGenerator.Generate:output_type -> pb.Mission
	2, // 8: pb.MissionGenerator.List:output_type -> pb.Mission
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mission_generator_proto_init() }
func file_mission_generator_proto_init() {
	if File_mission_generator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mission_generator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Twist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Objective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mission_generator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission_Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mission_generator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mission_generator_proto_goTypes,
		DependencyIndexes: file_mission_generator_proto_depIdxs,
		EnumInfos:         file_mission_generator_proto_enumTypes,
		MessageInfos:      file_mission_generator_proto_msgTypes,
	}.Build()
	File_mission_generator_proto = out.File
	file_mission_generator_proto_rawDesc = nil
	file_mission_generator_proto_goTypes = nil
	file_mission_generator_proto_depIdxs = nil
}
